import Head from 'next/head'
import { Inter } from '@next/font/google'
import styled from 'styled-components'
import Navbar from '@/components/Navbar'
import Sidebar from '../components/Sidebar'
import Feed from '@/container/Feed'
import { fetchAPI } from '@/utlis/fetchapi'
import {useEffect, useState} from "react";


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
    const [videos, setVideos] = useState(null)
    const [query, setQuery] = useState('New')

    useEffect(() => {
        fetchAPI(`search?part=snippet&q=${query}`)
            .then(res => setVideos(res.items))
            .catch(err => console.log(err))
    }, [query])


  return (
    <>
      <Head>
        <title>YouTubeV2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        <Sidebar query={query} setQuery={setQuery} />
        <Feed videos={videos}/>
       
      </main>
    </>
  )
}
