import Head from 'next/head'
import { Inter } from '@next/font/google'
import styled from 'styled-components'
import Navbar from '@/components/Navbar'
import Sidebar from '../components/Sidebar'
import Feed from '@/container/Feed'
import {useEffect, useState} from "react";
import useFetchPopular from '@/utlis/hooks/useFetchPopular'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
    const [videos, setVideos] = useState(null)
    const [query, setQuery] = useState('New')
    const {response, error, loading } = useFetchPopular()

    // useEffect(() => {
    //   getVideos()
    // }, [])

    // const getVideos = async () => {
    //   const data = await fetch(YOUTUBE_VIDEOS_API)
    //   const res = await data.json()
    //   setVideos(res.items)
    //   console.log(res.items)
    // }


  return (
    <>
      <Head>
        <title>YouTubeV2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        <Container>
        <Sidebar query={query} setQuery={setQuery} />
        <Feed videos={response} />
        </Container>
        
       
      </main>
    </>
  )
}

const Container = styled.div`
    display: flex;
    width: 100%;
    height: 100%;
    overflow-x: hidden;
    
    `